[package]
name = "datafusion-monoid"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "56.2.0"
arrow-schema = { version = "56.1.0", features = ["serde"] }
datafusion = "50.3.0"

[dev-dependencies]
tokio = { version = "1.45.1", features = ["full", "time"] }
